# use ubuntu linux.
os: linux
dist: trusty

# run in container.
sudo: false

# use java environment.
language: java

# install the newest java jdk8.
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# keep gradle build cache.
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# print environment.
before_script:
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $GRADLE_OPT

# skip install stage.
install: true

# run gradle build.
script:
  - ./gradlew build --info
  - ./gradlew check --info
